version: '3.8'

services:
  backend:
    build: ./backend
    ports: ["5000:80"]
    depends_on: [db]
  
  frontend:
    build: ./frontend
    ports: ["8080:80"]
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: example